webtalk_init -webtalk_dir C:\\Users\\isaac\\Dev\\FPGA\\ece532\\ml_microblaze_opt\\ml_microblaze_opt.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2026-02-23 22:15:28" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "kkvf0adce1a24f61h9vfdl8lo4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_12" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 9 4900HS with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2994 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.557 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1771896123326" -context "sdk\\\\bsp/1771896123326"
webtalk_add_data -client sdk -key hwid -value "1771873847170" -context "sdk\\\\bsp/1771896123326"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1771896123326"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1771896123326"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1771896123326"
webtalk_add_data -client sdk -key uid -value "1771896125142" -context "sdk\\\\application/1771896125142"
webtalk_add_data -client sdk -key hwid -value "1771873847170" -context "sdk\\\\application/1771896125142"
webtalk_add_data -client sdk -key bspid -value "1771896123326" -context "sdk\\\\application/1771896125142"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1771896125142"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1771896125142"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1771896125142"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1771896125142"
webtalk_add_data -client sdk -key LangUsed -value "CPP" -context "sdk\\\\application/1771896125142"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1771896125142"
webtalk_add_data -client sdk -key projSize -value "14.9453125" -context "sdk\\\\application/1771896125142"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1771902928919"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1771902928919"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1771902928919"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1771902928919"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1771902928919"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1771902928919"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1771902928919"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1771902928919"
webtalk_transmit -clientid 4087123697 -regid "" -xml C:\\Users\\isaac\\Dev\\FPGA\\ece532\\ml_microblaze_opt\\ml_microblaze_opt.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\isaac\\Dev\\FPGA\\ece532\\ml_microblaze_opt\\ml_microblaze_opt.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\isaac\\Dev\\FPGA\\ece532\\ml_microblaze_opt\\ml_microblaze_opt.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
