################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CC_SRCS += \
../tensorflow/lite/micro/kernels/activations.cc \
../tensorflow/lite/micro/kernels/activations_common.cc \
../tensorflow/lite/micro/kernels/add.cc \
../tensorflow/lite/micro/kernels/add_common.cc \
../tensorflow/lite/micro/kernels/add_n.cc \
../tensorflow/lite/micro/kernels/arg_min_max.cc \
../tensorflow/lite/micro/kernels/assign_variable.cc \
../tensorflow/lite/micro/kernels/batch_matmul.cc \
../tensorflow/lite/micro/kernels/batch_matmul_common.cc \
../tensorflow/lite/micro/kernels/batch_to_space_nd.cc \
../tensorflow/lite/micro/kernels/broadcast_args.cc \
../tensorflow/lite/micro/kernels/broadcast_to.cc \
../tensorflow/lite/micro/kernels/call_once.cc \
../tensorflow/lite/micro/kernels/cast.cc \
../tensorflow/lite/micro/kernels/ceil.cc \
../tensorflow/lite/micro/kernels/circular_buffer.cc \
../tensorflow/lite/micro/kernels/circular_buffer_common.cc \
../tensorflow/lite/micro/kernels/comparisons.cc \
../tensorflow/lite/micro/kernels/concatenation.cc \
../tensorflow/lite/micro/kernels/conv.cc \
../tensorflow/lite/micro/kernels/conv_common.cc \
../tensorflow/lite/micro/kernels/cumsum.cc \
../tensorflow/lite/micro/kernels/decode.cc \
../tensorflow/lite/micro/kernels/decode_state.cc \
../tensorflow/lite/micro/kernels/decode_state_huffman.cc \
../tensorflow/lite/micro/kernels/decode_state_lut.cc \
../tensorflow/lite/micro/kernels/decode_state_prune.cc \
../tensorflow/lite/micro/kernels/decompress.cc \
../tensorflow/lite/micro/kernels/decompress_common.cc \
../tensorflow/lite/micro/kernels/depth_to_space.cc \
../tensorflow/lite/micro/kernels/depthwise_conv.cc \
../tensorflow/lite/micro/kernels/depthwise_conv_common.cc \
../tensorflow/lite/micro/kernels/dequantize.cc \
../tensorflow/lite/micro/kernels/dequantize_common.cc \
../tensorflow/lite/micro/kernels/detection_postprocess.cc \
../tensorflow/lite/micro/kernels/div.cc \
../tensorflow/lite/micro/kernels/dynamic_update_slice.cc \
../tensorflow/lite/micro/kernels/elementwise.cc \
../tensorflow/lite/micro/kernels/elu.cc \
../tensorflow/lite/micro/kernels/embedding_lookup.cc \
../tensorflow/lite/micro/kernels/ethosu.cc \
../tensorflow/lite/micro/kernels/exp.cc \
../tensorflow/lite/micro/kernels/expand_dims.cc \
../tensorflow/lite/micro/kernels/fill.cc \
../tensorflow/lite/micro/kernels/floor.cc \
../tensorflow/lite/micro/kernels/floor_div.cc \
../tensorflow/lite/micro/kernels/floor_mod.cc \
../tensorflow/lite/micro/kernels/fully_connected.cc \
../tensorflow/lite/micro/kernels/fully_connected_common.cc \
../tensorflow/lite/micro/kernels/gather.cc \
../tensorflow/lite/micro/kernels/gather_nd.cc \
../tensorflow/lite/micro/kernels/hard_swish.cc \
../tensorflow/lite/micro/kernels/hard_swish_common.cc \
../tensorflow/lite/micro/kernels/if.cc \
../tensorflow/lite/micro/kernels/kernel_runner.cc \
../tensorflow/lite/micro/kernels/kernel_util.cc \
../tensorflow/lite/micro/kernels/l2_pool_2d.cc \
../tensorflow/lite/micro/kernels/l2norm.cc \
../tensorflow/lite/micro/kernels/leaky_relu.cc \
../tensorflow/lite/micro/kernels/leaky_relu_common.cc \
../tensorflow/lite/micro/kernels/log_softmax.cc \
../tensorflow/lite/micro/kernels/logical.cc \
../tensorflow/lite/micro/kernels/logical_common.cc \
../tensorflow/lite/micro/kernels/logistic.cc \
../tensorflow/lite/micro/kernels/logistic_common.cc \
../tensorflow/lite/micro/kernels/lstm_eval.cc \
../tensorflow/lite/micro/kernels/lstm_eval_common.cc \
../tensorflow/lite/micro/kernels/maximum_minimum.cc \
../tensorflow/lite/micro/kernels/micro_tensor_utils.cc \
../tensorflow/lite/micro/kernels/mirror_pad.cc \
../tensorflow/lite/micro/kernels/mul.cc \
../tensorflow/lite/micro/kernels/mul_common.cc \
../tensorflow/lite/micro/kernels/neg.cc \
../tensorflow/lite/micro/kernels/pack.cc \
../tensorflow/lite/micro/kernels/pad.cc \
../tensorflow/lite/micro/kernels/pad_common.cc \
../tensorflow/lite/micro/kernels/pooling.cc \
../tensorflow/lite/micro/kernels/pooling_common.cc \
../tensorflow/lite/micro/kernels/prelu.cc \
../tensorflow/lite/micro/kernels/prelu_common.cc \
../tensorflow/lite/micro/kernels/quantize.cc \
../tensorflow/lite/micro/kernels/quantize_common.cc \
../tensorflow/lite/micro/kernels/read_variable.cc \
../tensorflow/lite/micro/kernels/reduce.cc \
../tensorflow/lite/micro/kernels/reduce_common.cc \
../tensorflow/lite/micro/kernels/reshape.cc \
../tensorflow/lite/micro/kernels/reshape_common.cc \
../tensorflow/lite/micro/kernels/resize_bilinear.cc \
../tensorflow/lite/micro/kernels/resize_nearest_neighbor.cc \
../tensorflow/lite/micro/kernels/reverse.cc \
../tensorflow/lite/micro/kernels/round.cc \
../tensorflow/lite/micro/kernels/select.cc \
../tensorflow/lite/micro/kernels/shape.cc \
../tensorflow/lite/micro/kernels/slice.cc \
../tensorflow/lite/micro/kernels/softmax.cc \
../tensorflow/lite/micro/kernels/softmax_common.cc \
../tensorflow/lite/micro/kernels/space_to_batch_nd.cc \
../tensorflow/lite/micro/kernels/space_to_depth.cc \
../tensorflow/lite/micro/kernels/split.cc \
../tensorflow/lite/micro/kernels/split_v.cc \
../tensorflow/lite/micro/kernels/squared_difference.cc \
../tensorflow/lite/micro/kernels/squeeze.cc \
../tensorflow/lite/micro/kernels/strided_slice.cc \
../tensorflow/lite/micro/kernels/strided_slice_common.cc \
../tensorflow/lite/micro/kernels/sub.cc \
../tensorflow/lite/micro/kernels/sub_common.cc \
../tensorflow/lite/micro/kernels/svdf.cc \
../tensorflow/lite/micro/kernels/svdf_common.cc \
../tensorflow/lite/micro/kernels/tanh.cc \
../tensorflow/lite/micro/kernels/transpose.cc \
../tensorflow/lite/micro/kernels/transpose_common.cc \
../tensorflow/lite/micro/kernels/transpose_conv.cc \
../tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.cc \
../tensorflow/lite/micro/kernels/unpack.cc \
../tensorflow/lite/micro/kernels/var_handle.cc \
../tensorflow/lite/micro/kernels/while.cc \
../tensorflow/lite/micro/kernels/zeros_like.cc 

CC_DEPS += \
./tensorflow/lite/micro/kernels/activations.d \
./tensorflow/lite/micro/kernels/activations_common.d \
./tensorflow/lite/micro/kernels/add.d \
./tensorflow/lite/micro/kernels/add_common.d \
./tensorflow/lite/micro/kernels/add_n.d \
./tensorflow/lite/micro/kernels/arg_min_max.d \
./tensorflow/lite/micro/kernels/assign_variable.d \
./tensorflow/lite/micro/kernels/batch_matmul.d \
./tensorflow/lite/micro/kernels/batch_matmul_common.d \
./tensorflow/lite/micro/kernels/batch_to_space_nd.d \
./tensorflow/lite/micro/kernels/broadcast_args.d \
./tensorflow/lite/micro/kernels/broadcast_to.d \
./tensorflow/lite/micro/kernels/call_once.d \
./tensorflow/lite/micro/kernels/cast.d \
./tensorflow/lite/micro/kernels/ceil.d \
./tensorflow/lite/micro/kernels/circular_buffer.d \
./tensorflow/lite/micro/kernels/circular_buffer_common.d \
./tensorflow/lite/micro/kernels/comparisons.d \
./tensorflow/lite/micro/kernels/concatenation.d \
./tensorflow/lite/micro/kernels/conv.d \
./tensorflow/lite/micro/kernels/conv_common.d \
./tensorflow/lite/micro/kernels/cumsum.d \
./tensorflow/lite/micro/kernels/decode.d \
./tensorflow/lite/micro/kernels/decode_state.d \
./tensorflow/lite/micro/kernels/decode_state_huffman.d \
./tensorflow/lite/micro/kernels/decode_state_lut.d \
./tensorflow/lite/micro/kernels/decode_state_prune.d \
./tensorflow/lite/micro/kernels/decompress.d \
./tensorflow/lite/micro/kernels/decompress_common.d \
./tensorflow/lite/micro/kernels/depth_to_space.d \
./tensorflow/lite/micro/kernels/depthwise_conv.d \
./tensorflow/lite/micro/kernels/depthwise_conv_common.d \
./tensorflow/lite/micro/kernels/dequantize.d \
./tensorflow/lite/micro/kernels/dequantize_common.d \
./tensorflow/lite/micro/kernels/detection_postprocess.d \
./tensorflow/lite/micro/kernels/div.d \
./tensorflow/lite/micro/kernels/dynamic_update_slice.d \
./tensorflow/lite/micro/kernels/elementwise.d \
./tensorflow/lite/micro/kernels/elu.d \
./tensorflow/lite/micro/kernels/embedding_lookup.d \
./tensorflow/lite/micro/kernels/ethosu.d \
./tensorflow/lite/micro/kernels/exp.d \
./tensorflow/lite/micro/kernels/expand_dims.d \
./tensorflow/lite/micro/kernels/fill.d \
./tensorflow/lite/micro/kernels/floor.d \
./tensorflow/lite/micro/kernels/floor_div.d \
./tensorflow/lite/micro/kernels/floor_mod.d \
./tensorflow/lite/micro/kernels/fully_connected.d \
./tensorflow/lite/micro/kernels/fully_connected_common.d \
./tensorflow/lite/micro/kernels/gather.d \
./tensorflow/lite/micro/kernels/gather_nd.d \
./tensorflow/lite/micro/kernels/hard_swish.d \
./tensorflow/lite/micro/kernels/hard_swish_common.d \
./tensorflow/lite/micro/kernels/if.d \
./tensorflow/lite/micro/kernels/kernel_runner.d \
./tensorflow/lite/micro/kernels/kernel_util.d \
./tensorflow/lite/micro/kernels/l2_pool_2d.d \
./tensorflow/lite/micro/kernels/l2norm.d \
./tensorflow/lite/micro/kernels/leaky_relu.d \
./tensorflow/lite/micro/kernels/leaky_relu_common.d \
./tensorflow/lite/micro/kernels/log_softmax.d \
./tensorflow/lite/micro/kernels/logical.d \
./tensorflow/lite/micro/kernels/logical_common.d \
./tensorflow/lite/micro/kernels/logistic.d \
./tensorflow/lite/micro/kernels/logistic_common.d \
./tensorflow/lite/micro/kernels/lstm_eval.d \
./tensorflow/lite/micro/kernels/lstm_eval_common.d \
./tensorflow/lite/micro/kernels/maximum_minimum.d \
./tensorflow/lite/micro/kernels/micro_tensor_utils.d \
./tensorflow/lite/micro/kernels/mirror_pad.d \
./tensorflow/lite/micro/kernels/mul.d \
./tensorflow/lite/micro/kernels/mul_common.d \
./tensorflow/lite/micro/kernels/neg.d \
./tensorflow/lite/micro/kernels/pack.d \
./tensorflow/lite/micro/kernels/pad.d \
./tensorflow/lite/micro/kernels/pad_common.d \
./tensorflow/lite/micro/kernels/pooling.d \
./tensorflow/lite/micro/kernels/pooling_common.d \
./tensorflow/lite/micro/kernels/prelu.d \
./tensorflow/lite/micro/kernels/prelu_common.d \
./tensorflow/lite/micro/kernels/quantize.d \
./tensorflow/lite/micro/kernels/quantize_common.d \
./tensorflow/lite/micro/kernels/read_variable.d \
./tensorflow/lite/micro/kernels/reduce.d \
./tensorflow/lite/micro/kernels/reduce_common.d \
./tensorflow/lite/micro/kernels/reshape.d \
./tensorflow/lite/micro/kernels/reshape_common.d \
./tensorflow/lite/micro/kernels/resize_bilinear.d \
./tensorflow/lite/micro/kernels/resize_nearest_neighbor.d \
./tensorflow/lite/micro/kernels/reverse.d \
./tensorflow/lite/micro/kernels/round.d \
./tensorflow/lite/micro/kernels/select.d \
./tensorflow/lite/micro/kernels/shape.d \
./tensorflow/lite/micro/kernels/slice.d \
./tensorflow/lite/micro/kernels/softmax.d \
./tensorflow/lite/micro/kernels/softmax_common.d \
./tensorflow/lite/micro/kernels/space_to_batch_nd.d \
./tensorflow/lite/micro/kernels/space_to_depth.d \
./tensorflow/lite/micro/kernels/split.d \
./tensorflow/lite/micro/kernels/split_v.d \
./tensorflow/lite/micro/kernels/squared_difference.d \
./tensorflow/lite/micro/kernels/squeeze.d \
./tensorflow/lite/micro/kernels/strided_slice.d \
./tensorflow/lite/micro/kernels/strided_slice_common.d \
./tensorflow/lite/micro/kernels/sub.d \
./tensorflow/lite/micro/kernels/sub_common.d \
./tensorflow/lite/micro/kernels/svdf.d \
./tensorflow/lite/micro/kernels/svdf_common.d \
./tensorflow/lite/micro/kernels/tanh.d \
./tensorflow/lite/micro/kernels/transpose.d \
./tensorflow/lite/micro/kernels/transpose_common.d \
./tensorflow/lite/micro/kernels/transpose_conv.d \
./tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.d \
./tensorflow/lite/micro/kernels/unpack.d \
./tensorflow/lite/micro/kernels/var_handle.d \
./tensorflow/lite/micro/kernels/while.d \
./tensorflow/lite/micro/kernels/zeros_like.d 

OBJS += \
./tensorflow/lite/micro/kernels/activations.o \
./tensorflow/lite/micro/kernels/activations_common.o \
./tensorflow/lite/micro/kernels/add.o \
./tensorflow/lite/micro/kernels/add_common.o \
./tensorflow/lite/micro/kernels/add_n.o \
./tensorflow/lite/micro/kernels/arg_min_max.o \
./tensorflow/lite/micro/kernels/assign_variable.o \
./tensorflow/lite/micro/kernels/batch_matmul.o \
./tensorflow/lite/micro/kernels/batch_matmul_common.o \
./tensorflow/lite/micro/kernels/batch_to_space_nd.o \
./tensorflow/lite/micro/kernels/broadcast_args.o \
./tensorflow/lite/micro/kernels/broadcast_to.o \
./tensorflow/lite/micro/kernels/call_once.o \
./tensorflow/lite/micro/kernels/cast.o \
./tensorflow/lite/micro/kernels/ceil.o \
./tensorflow/lite/micro/kernels/circular_buffer.o \
./tensorflow/lite/micro/kernels/circular_buffer_common.o \
./tensorflow/lite/micro/kernels/comparisons.o \
./tensorflow/lite/micro/kernels/concatenation.o \
./tensorflow/lite/micro/kernels/conv.o \
./tensorflow/lite/micro/kernels/conv_common.o \
./tensorflow/lite/micro/kernels/cumsum.o \
./tensorflow/lite/micro/kernels/decode.o \
./tensorflow/lite/micro/kernels/decode_state.o \
./tensorflow/lite/micro/kernels/decode_state_huffman.o \
./tensorflow/lite/micro/kernels/decode_state_lut.o \
./tensorflow/lite/micro/kernels/decode_state_prune.o \
./tensorflow/lite/micro/kernels/decompress.o \
./tensorflow/lite/micro/kernels/decompress_common.o \
./tensorflow/lite/micro/kernels/depth_to_space.o \
./tensorflow/lite/micro/kernels/depthwise_conv.o \
./tensorflow/lite/micro/kernels/depthwise_conv_common.o \
./tensorflow/lite/micro/kernels/dequantize.o \
./tensorflow/lite/micro/kernels/dequantize_common.o \
./tensorflow/lite/micro/kernels/detection_postprocess.o \
./tensorflow/lite/micro/kernels/div.o \
./tensorflow/lite/micro/kernels/dynamic_update_slice.o \
./tensorflow/lite/micro/kernels/elementwise.o \
./tensorflow/lite/micro/kernels/elu.o \
./tensorflow/lite/micro/kernels/embedding_lookup.o \
./tensorflow/lite/micro/kernels/ethosu.o \
./tensorflow/lite/micro/kernels/exp.o \
./tensorflow/lite/micro/kernels/expand_dims.o \
./tensorflow/lite/micro/kernels/fill.o \
./tensorflow/lite/micro/kernels/floor.o \
./tensorflow/lite/micro/kernels/floor_div.o \
./tensorflow/lite/micro/kernels/floor_mod.o \
./tensorflow/lite/micro/kernels/fully_connected.o \
./tensorflow/lite/micro/kernels/fully_connected_common.o \
./tensorflow/lite/micro/kernels/gather.o \
./tensorflow/lite/micro/kernels/gather_nd.o \
./tensorflow/lite/micro/kernels/hard_swish.o \
./tensorflow/lite/micro/kernels/hard_swish_common.o \
./tensorflow/lite/micro/kernels/if.o \
./tensorflow/lite/micro/kernels/kernel_runner.o \
./tensorflow/lite/micro/kernels/kernel_util.o \
./tensorflow/lite/micro/kernels/l2_pool_2d.o \
./tensorflow/lite/micro/kernels/l2norm.o \
./tensorflow/lite/micro/kernels/leaky_relu.o \
./tensorflow/lite/micro/kernels/leaky_relu_common.o \
./tensorflow/lite/micro/kernels/log_softmax.o \
./tensorflow/lite/micro/kernels/logical.o \
./tensorflow/lite/micro/kernels/logical_common.o \
./tensorflow/lite/micro/kernels/logistic.o \
./tensorflow/lite/micro/kernels/logistic_common.o \
./tensorflow/lite/micro/kernels/lstm_eval.o \
./tensorflow/lite/micro/kernels/lstm_eval_common.o \
./tensorflow/lite/micro/kernels/maximum_minimum.o \
./tensorflow/lite/micro/kernels/micro_tensor_utils.o \
./tensorflow/lite/micro/kernels/mirror_pad.o \
./tensorflow/lite/micro/kernels/mul.o \
./tensorflow/lite/micro/kernels/mul_common.o \
./tensorflow/lite/micro/kernels/neg.o \
./tensorflow/lite/micro/kernels/pack.o \
./tensorflow/lite/micro/kernels/pad.o \
./tensorflow/lite/micro/kernels/pad_common.o \
./tensorflow/lite/micro/kernels/pooling.o \
./tensorflow/lite/micro/kernels/pooling_common.o \
./tensorflow/lite/micro/kernels/prelu.o \
./tensorflow/lite/micro/kernels/prelu_common.o \
./tensorflow/lite/micro/kernels/quantize.o \
./tensorflow/lite/micro/kernels/quantize_common.o \
./tensorflow/lite/micro/kernels/read_variable.o \
./tensorflow/lite/micro/kernels/reduce.o \
./tensorflow/lite/micro/kernels/reduce_common.o \
./tensorflow/lite/micro/kernels/reshape.o \
./tensorflow/lite/micro/kernels/reshape_common.o \
./tensorflow/lite/micro/kernels/resize_bilinear.o \
./tensorflow/lite/micro/kernels/resize_nearest_neighbor.o \
./tensorflow/lite/micro/kernels/reverse.o \
./tensorflow/lite/micro/kernels/round.o \
./tensorflow/lite/micro/kernels/select.o \
./tensorflow/lite/micro/kernels/shape.o \
./tensorflow/lite/micro/kernels/slice.o \
./tensorflow/lite/micro/kernels/softmax.o \
./tensorflow/lite/micro/kernels/softmax_common.o \
./tensorflow/lite/micro/kernels/space_to_batch_nd.o \
./tensorflow/lite/micro/kernels/space_to_depth.o \
./tensorflow/lite/micro/kernels/split.o \
./tensorflow/lite/micro/kernels/split_v.o \
./tensorflow/lite/micro/kernels/squared_difference.o \
./tensorflow/lite/micro/kernels/squeeze.o \
./tensorflow/lite/micro/kernels/strided_slice.o \
./tensorflow/lite/micro/kernels/strided_slice_common.o \
./tensorflow/lite/micro/kernels/sub.o \
./tensorflow/lite/micro/kernels/sub_common.o \
./tensorflow/lite/micro/kernels/svdf.o \
./tensorflow/lite/micro/kernels/svdf_common.o \
./tensorflow/lite/micro/kernels/tanh.o \
./tensorflow/lite/micro/kernels/transpose.o \
./tensorflow/lite/micro/kernels/transpose_common.o \
./tensorflow/lite/micro/kernels/transpose_conv.o \
./tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.o \
./tensorflow/lite/micro/kernels/unpack.o \
./tensorflow/lite/micro/kernels/var_handle.o \
./tensorflow/lite/micro/kernels/while.o \
./tensorflow/lite/micro/kernels/zeros_like.o 


# Each subdirectory must supply rules for building sources it contributes
tensorflow/lite/micro/kernels/%.o: ../tensorflow/lite/micro/kernels/%.cc
	@echo 'Building file: $<'
	@echo 'Invoking: MicroBlaze g++ compiler'
	mb-g++ -Wall -O0 -g3 -c -fmessage-length=0 -MT"$@" -I../../fastdepth_runtime_bsp/microblaze_0/include -mlittle-endian -mxl-barrel-shift -mxl-pattern-compare -mno-xl-soft-div -mcpu=v11.0 -mno-xl-soft-mul -mxl-multiply-high -mhard-float -mxl-float-convert -mxl-float-sqrt -Wl,--no-relax -ffunction-sections -fdata-sections -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


